language: python
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install -U pip
  - pip install poetry
install:
  - poetry install
  - >-
    poetry run pip install https://github.com/rogerbinns/apsw/releases/download/3.32.2-r1/apsw-3.32.2-r1.zip
    --global-option=fetch --global-option=--version --global-option=3.32.2 --global-option=--all
    --global-option=build --global-option=--enable-all-extensions
script:
  - mypy .
  - black aiosql tests --check
  - pytest tests
stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request
jobs:
  include:
    - stage: deploy
      python: "3.8"
      script: skip
      before_deploy:
        - poetry run mkdocs build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: true
        local-dir: site
        on:
          branch: master
env:
  global:
    secure: D1uoEHKEuZ2rYjYVbJVYtoeNBqyRKFglFLj0An0jDbxPuj5zQ8bcX5bmZ91vkucGqWS9TQzDF2l6DHLHqzSSaCeKb+lj/AGeC+7Bssxpm8iNgtv9ITXbUhnnc4VKay1jpR1MrXgHySeHSyHPN0Zq3LIADsAB6NbF+KB6k9zRS8t5fFlpY+zNY8VmknP7Q9excrmVb5xotCUQCcAs5P1BqJWf+lTVNQzCSMQxYPna6SxVsJv3FBXwWUn1kFlOIedvZrSXml3x7Kh47ceR8Z6/5EmOekFejp02qT6jMSttgNFEaPHIL94kJSyTeTUkFp5MJap8LvJPTOimSWdgggm6AQXsc8v8uSHGHZ1ECZThOqW3cncvUigK7qOtpCzzQ0shPI2ARMX8+//ADRIvyY5OVoHbJTk/09f8aAj0pszOw25wKYb+ngarPoholCnGMLsEuIuIDcFXPYbouTmah+2gdmtsdQSdN7tJDrGKVoq9TrYaNGikplZjBJltQtPBoO6ThEtkkZEgL0SFYsI5LOYAjodjr82Zd5b62l3wfJNO4m1BearEoKVmXVRtsjW0h0tE95Cfl10WMUwRy8m19eMUZSfkxPVok+X5vR7Qb0ldyoLkJvfLsCgFZ6sJ24n29/nynWdWJd2SOUbHwh3iU4Nx474kMoO09lnhoEry3wx0d3k=
